# 0. 라이브러리 임포트

In [65]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from collections import Counter

# 1. 데이터 불러오기와 첫인사

In [66]:
# 올바른 경로로 입력하세요
info = pd.read_csv('vg_info.csv')
sale = pd.read_csv('vg_sales.csv')

In [67]:
print(info.shape)
print(sale.shape)

(16598, 6)
(16598, 8)

In [68]:
info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GAME_ID    16598 non-null  int64
 1   Name       16598 non-null  object
 2   Platform   16598 non-null  object
 3   Year       16327 non-null  float64
 4   Genre      16598 non-null  object
 5   Publisher  16540 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 778.2+ KB

In [69]:
print(info.isna().sum())

GAME_ID        0
Name           0
Platform       0
Year         271
Genre          0
Publisher     58
dtype: int64

In [70]:
info.nunique()

GAME_ID      16598
Name         11493
Platform        31
Year            39
Genre           12
Publisher      578
dtype: int64

In [71]:
sale.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   GAME_ID       16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   NA_Sales      16598 non-null  float64
 4   EU_Sales      16598 non-null  float64
 5   JP_Sales      16598 non-null  float64
 6   Other_Sales   16598 non-null  float64
 7   Global_Sales  16598 non-null  float64
dtypes: float64(5), int64(1), object(2)
memory usage: 1.0+ MB

In [72]:
sale.describe()

,GAME_ID,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [73]:
info.head()

   GAME_ID                      Name Platform    Year         Genre Publisher
0        1                Wii Sports      Wii  2006.0        Sports  Nintendo
1        2         Super Mario Bros.      NES  1985.0      Platform  Nintendo
2        3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo
3        4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo
4        5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo

In [74]:
sale.head()

,GAME_ID,Name,Platform,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,11.27,8.89,10.22,1.00,31.37

# 2. 테이블을 합치기

위 head를 보면, info 테이블은 특수문자 -> 숫자 -> abc 순으로 정렬이 되어 있고, sale 테이블은 글로벌 판매량을 기준으로 정렬되어 있습니다.

In [75]:
# 실습 1: 우선 GAME_ID를 기준으로 병합해봅시다.
# 참고로, DB에서는 병합의 기준이 되는 키를 Primary Key라고 부른다네요

df = pd.merge(sale, info, on='GAME_ID', how='inner')

print(df.shape)
df.head(10)

(16598, 13)

,GAME_ID,Name_x,Platform_x,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Name_y,Platform_y,Year,Genre,Publisher
0,1,Wii Sports,Wii,41.49,29.02,3.77,8.46,82.74,Wii Sports,Wii,2006.0,Sports,Nintendo
1,2,Super Mario Bros.,NES,29.08,3.58,6.81,0.77,40.24,Super Mario Bros.,NES,1985.0,Platform,Nintendo
2,3,Mario Kart Wii,Wii,15.85,12.88,3.79,3.31,35.82,Mario Kart Wii,Wii,2008.0,Racing,Nintendo
3,4,Wii Sports Resort,Wii,15.75,11.01,3.28,2.96,33.00,Wii Sports Resort,Wii,2009.0,Sports,Nintendo
4,5,Pokemon Red/Pokemon Blue,GB,11.27,8.89,10.22,1.00,31.37,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo
5,6,Tetris,GB,23.20,2.26,4.22,0.58,30.26,Tetris,GB,1989.0,Puzzle,Nintendo
6,7,New Super Mario Bros.,DS,11.38,9.23,6.50,2.90,30.01,New Super Mario Bros.,DS,2006.0,Platform,Nintendo
7,8,Wii Play,Wii,14.03,9.20,2.93,2.85,29.02,Wii Play,Wii,2006.0,Misc,Nintendo
8,9,New Super Mario Bros. Wii,Wii,14.59,7.06,4.70,2.26,28.62,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo
9,10,Duck Hunt,NES,26.93,0.63,0.28,0.47,28.31,Duck Hunt,NES,1984.0,Shooter,Nintendo

In [76]:
# Name_x, Name_y 이런 중복열이 생겨요...
# -> 기준(on)에 리스트 형식으로, 공통된 열을 다 넣어주세요.
df = pd.merge(sale, info, on=['GAME_ID', 'Name', 'Platform'], how='inner')

print(df.shape)
df.head(10)

(16598, 11)

,GAME_ID,Name,Platform,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Year,Genre,Publisher
0,1,Wii Sports,Wii,41.49,29.02,3.77,8.46,82.74,2006.0,Sports,Nintendo
1,2,Super Mario Bros.,NES,29.08,3.58,6.81,0.77,40.24,1985.0,Platform,Nintendo
2,3,Mario Kart Wii,Wii,15.85,12.88,3.79,3.31,35.82,2008.0,Racing,Nintendo
3,4,Wii Sports Resort,Wii,15.75,11.01,3.28,2.96,33.00,2009.0,Sports,Nintendo
4,5,Pokemon Red/Pokemon Blue,GB,11.27,8.89,10.22,1.00,31.37,1996.0,Role-Playing,Nintendo
5,6,Tetris,GB,23.20,2.26,4.22,0.58,30.26,1989.0,Puzzle,Nintendo
6,7,New Super Mario Bros.,DS,11.38,9.23,6.50,2.90,30.01,2006.0,Platform,Nintendo
7,8,Wii Play,Wii,14.03,9.20,2.93,2.85,29.02,2006.0,Misc,Nintendo
8,9,New Super Mario Bros. Wii,Wii,14.59,7.06,4.70,2.26,28.62,2009.0,Platform,Nintendo
9,10,Duck Hunt,NES,26.93,0.63,0.28,0.47,28.31,1984.0,Shooter,Nintendo

In [77]:
# (여기는 그냥 실행만 해주세요)
sale_drop = sale.drop(columns=['GAME_ID'])
info_drop = info.drop(columns=['GAME_ID'])

In [78]:
# 만약 Primary Key인 GAME_ID가 없다면 어떻게 병합해야 할까요?

df_merged = pd.merge(sale_drop, info_drop, on=['Name','Platform'])

df_merged.shape

(16608, 10)

In [79]:
# 이름만을 Key로 하여 병합한다면 이런 일이 생깁니다.

df_merged_by_name = pd.merge(sale_drop, info_drop, on=['Name'])

df_merged_by_name.shape
# 행 수가 이상하게 늘어났죠?

(35230, 11)

In [80]:
# 여러 플랫폼으로 발매된 게임의 경우, 이름만으로 머지하면 이런 식으로 행 수가 늘어나 버립니다.
# 다대다(Many-to-Many) 병합이라고도 합니다.

df_merged_by_name.loc[df_merged_by_name['Name']=='Tetris'][['Name','Platform_x','Platform_y','Global_Sales']]

       Name Platform_x Platform_y  Global_Sales
6    Tetris         GB         GB         30.26
7    Tetris         GB        NES         30.26
339  Tetris        NES         GB          5.58
340  Tetris        NES        NES          5.58

In [81]:
# 올바르게 머지한 것도 볼까요?

df_merged.loc[df_merged['Name']=='Tetris'][['Name','Platform','Global_Sales']]

       Name Platform  Global_Sales
5    Tetris       GB         30.26
155  Tetris      NES          5.58

# 3. 데이터 뽑아보기

In [82]:
# 열 목록 보기
print(df.columns)

# 타입
print(type(df.columns))

# 리스트로 변환
print(list(df.columns))

Index(['GAME_ID', 'Name', 'Platform', 'NA_Sales', 'EU_Sales', 'JP_Sales',
       'Other_Sales', 'Global_Sales', 'Year', 'Genre', 'Publisher'],
      dtype='object')
<class 'pandas.core.indexes.base.Index'>
['GAME_ID', 'Name', 'Platform', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales', 'Year', 'Genre', 'Publisher']

In [83]:
# 단일 열만 인덱싱 - Series로 반환됨
print(type(df['Name']))
df['Name']

<class 'pandas.core.series.Series'>

0                                              Wii Sports
1                                       Super Mario Bros.
2                                          Mario Kart Wii
3                                       Wii Sports Resort
4                                Pokemon Red/Pokemon Blue
                               ...
16593                  Woody Woodpecker in Crazy Castle 5
16594                       Men in Black II: Alien Escape
16595    SCORE International Baja 1000: The Official Game
16596                                          Know How 2
16597                                    Spirits & Spells
Name: Name, Length: 16598, dtype: object

In [84]:
# Fancy 인덱싱 - 데이터프레임 형태를 유지
print(type(df[['Name']]))
df[['Name']]

<class 'pandas.core.frame.DataFrame'>

                                                   Name
0                                            Wii Sports
1                                     Super Mario Bros.
2                                        Mario Kart Wii
3                                     Wii Sports Resort
4                              Pokemon Red/Pokemon Blue
...                                                 ...
16593                Woody Woodpecker in Crazy Castle 5
16594                     Men in Black II: Alien Escape
16595  SCORE International Baja 1000: The Official Game
16596                                        Know How 2
16597                                  Spirits & Spells

[16598 rows x 1 columns]

In [85]:
# 여러가지 열을 추출할 때는 Fancy 인덱싱을 해주어야 합니다
# 이름, 배급사, 플랫폼, 출시년도 순으로 Fancy 인덱싱을 해주세요

df[['Name','Publisher','Platform','Year']]

,Name,Publisher,Platform,Year
0,Wii Sports,Nintendo,Wii,2006.0
1,Super Mario Bros.,Nintendo,NES,1985.0
2,Mario Kart Wii,Nintendo,Wii,2008.0
3,Wii Sports Resort,Nintendo,Wii,2009.0
4,Pokemon Red/Pokemon Blue,Nintendo,GB,1996.0
...,...,...,...,...
16593,Woody Woodpecker in Crazy Castle 5,Kemco,GBA,2002.0
16594,Men in Black II: Alien Escape,Infogrames,GC,2003.0
16595,SCORE International Baja 1000: The Official Game,Activision,PS2,2008.0
16596,Know How 2,7G//AMES,DS,2010.0
16597,Spirits & Spells,Wanadoo,GBA,2003.0

In [86]:
# loc으로 인덱싱과 슬라이싱

df.loc[3,:]

GAME_ID                         4
Name            Wii Sports Resort
Platform                      Wii
NA_Sales                    15.75
EU_Sales                    11.01
JP_Sales                     3.28
Other_Sales                  2.96
Global_Sales                 33.0
Year                       2009.0
Genre                      Sports
Publisher                Nintendo
Name: 3, dtype: object

In [87]:
df.loc[:,'Publisher']

0          Nintendo
1          Nintendo
2          Nintendo
3          Nintendo
4          Nintendo
            ...
16593         Kemco
16594    Infogrames
16595    Activision
16596      7G//AMES
16597       Wanadoo
Name: Publisher, Length: 16598, dtype: object

In [88]:
# loc 슬라이싱은 end 인덱스를 포함합니다.
df.loc[3:6,:]

,GAME_ID,Name,Platform,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Year,Genre,Publisher
3,4,Wii Sports Resort,Wii,15.75,11.01,3.28,2.96,33.00,2009.0,Sports,Nintendo
4,5,Pokemon Red/Pokemon Blue,GB,11.27,8.89,10.22,1.00,31.37,1996.0,Role-Playing,Nintendo
5,6,Tetris,GB,23.20,2.26,4.22,0.58,30.26,1989.0,Puzzle,Nintendo
6,7,New Super Mario Bros.,DS,11.38,9.23,6.50,2.90,30.01,2006.0,Platform,Nintendo

In [89]:
df.loc[10:15,'NA_Sales':'Global_Sales']

    NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
10      9.07     11.00      1.93         2.75         24.76
11      9.81      7.57      4.13         1.92         23.42
12      9.00      6.18      7.20         0.71         23.10
13      8.94      8.03      3.60         2.15         22.72
14      9.09      8.59      2.53         1.79         22.00
15     14.97      4.94      0.24         1.67         21.82

In [90]:
# 슬라이싱에도 step을 지정할 수 있습니다.
df.loc[10:20:2, ['Name','Global_Sales']]

                             Name  Global_Sales
10                     Nintendogs         24.76
12    Pokemon Gold/Pokemon Silver         23.10
14                   Wii Fit Plus         22.00
16             Grand Theft Auto V         21.40
18              Super Mario World         20.61
20  Pokemon Diamond/Pokemon Pearl         18.36

In [91]:
print(df.loc[10:20:2, ['Name','Global_Sales']])

                             Name  Global_Sales
10                     Nintendogs         24.76
12    Pokemon Gold/Pokemon Silver         23.10
14                   Wii Fit Plus         22.00
16             Grand Theft Auto V         21.40
18              Super Mario World         20.61
20  Pokemon Diamond/Pokemon Pearl         18.36

In [92]:
# iloc으로 인덱싱과 슬라이싱

df.iloc[3,:]

GAME_ID                         4
Name            Wii Sports Resort
Platform                      Wii
NA_Sales                    15.75
EU_Sales                    11.01
JP_Sales                     3.28
Other_Sales                  2.96
Global_Sales                 33.0
Year                       2009.0
Genre                      Sports
Publisher                Nintendo
Name: 3, dtype: object

In [93]:
df.iloc[:,-1]

0          Nintendo
1          Nintendo
2          Nintendo
3          Nintendo
4          Nintendo
            ...
16593         Kemco
16594    Infogrames
16595    Activision
16596      7G//AMES
16597       Wanadoo
Name: Publisher, Length: 16598, dtype: object

In [94]:
# iloc 슬라이싱은 end 인덱스를 포함하지 않습니다
df.iloc[3:6,:]

,GAME_ID,Name,Platform,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Year,Genre,Publisher
3,4,Wii Sports Resort,Wii,15.75,11.01,3.28,2.96,33.00,2009.0,Sports,Nintendo
4,5,Pokemon Red/Pokemon Blue,GB,11.27,8.89,10.22,1.00,31.37,1996.0,Role-Playing,Nintendo
5,6,Tetris,GB,23.20,2.26,4.22,0.58,30.26,1989.0,Puzzle,Nintendo

In [95]:
# iloc 슬라이싱은 열도 인덱스 번호로 써줘야 합니다. (loc처럼 열 이름으로 하면 ValueError)
df.iloc[10:15,3:8]

    NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
10      9.07     11.00      1.93         2.75         24.76
11      9.81      7.57      4.13         1.92         23.42
12      9.00      6.18      7.20         0.71         23.10
13      8.94      8.03      3.60         2.15         22.72
14      9.09      8.59      2.53         1.79         22.00

In [96]:
df.iloc[30:40:3, [2,5,6]]

   Platform  JP_Sales  Other_Sales
30       GB      3.12         0.59
33      PS4      0.35         2.31
36     X360      0.08         1.29
39      Wii      2.66         1.02

In [97]:
# 불리언 인덱싱 - 단일

# df[조건문] 으로 필터링합니다.
# 조건문이 참인 행만 뽑아주는 인덱싱입니다!

df[df['Publisher'] == 'Nintendo'].sample(5)

,GAME_ID,Name,Platform,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Year,Genre,Publisher
1267,1269,Final Fantasy: Crystal Chronicles,GC,0.72,0.38,0.36,0.04,1.49,2003.0,Role-Playing,Nintendo
16123,16126,Nintendogs and Cats Golden Retriever and New F...,3DS,0.00,0.01,0.00,0.00,0.01,2011.0,Action,Nintendo
5191,5193,Hamtaro: Ham-Ham Heartbreak,GBA,0.26,0.10,0.00,0.01,0.36,2002.0,Action,Nintendo
6263,6265,Moero! Nekketsu Rhythm Damashii: Osu! Tatakae!...,DS,0.00,0.00,0.27,0.00,0.27,2007.0,Misc,Nintendo
672,674,Donkey Kong Land II,GB,1.39,0.48,0.40,0.08,2.35,1996.0,Platform,Nintendo

In [98]:
# 불리언 인덱싱 - 반대 조건으로 찾기

df[~(df['Publisher'] == 'Nintendo')].head()

,GAME_ID,Name,Platform,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Year,Genre,Publisher
15,16,Kinect Adventures!,X360,14.97,4.94,0.24,1.67,21.82,2010.0,Misc,Microsoft Game Studios
16,17,Grand Theft Auto V,PS3,7.01,9.27,0.97,4.14,21.40,2013.0,Action,Take-Two Interactive
17,18,Grand Theft Auto: San Andreas,PS2,9.43,0.40,0.41,10.57,20.81,2004.0,Action,Take-Two Interactive
23,24,Grand Theft Auto V,X360,9.63,5.31,0.06,1.38,16.38,2013.0,Action,Take-Two Interactive
24,25,Grand Theft Auto: Vice City,PS2,8.41,5.49,0.47,1.78,16.15,2002.0,Action,Take-Two Interactive

In [99]:
# 불리언 인덱싱 - 여러 조건
# 각각의 조건문을 ()로 감싸준 뒤, |과 & 연산자를 사이에 넣어서 여러 조건문을 통한 필터링을 할 수 있습니다.

# df[(조건문1) & (조건문2)]
# -> 조건 1 그리고 2에 모두 해당하는 행 필터링

# df[(조건문1) | (조건문2)]
# -> 조건 1 또는 2에 해당하는 행 필터링



# 실습 2: 퍼블리셔가 닌텐도이고, 플랫폼이 Wii이고, 글로벌 판매량이 100만장 이상인(밀리언셀러) 게임을 찾으세요.
# 1.0 = 1 million 입니다.

df[(df['Publisher']=='Nintendo')&(df['Platform']=='Wii')&(df['Global_Sales']>=1.0)]

,GAME_ID,Name,Platform,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Year,Genre,Publisher
0,1,Wii Sports,Wii,41.49,29.02,3.77,8.46,82.74,2006.0,Sports,Nintendo
2,3,Mario Kart Wii,Wii,15.85,12.88,3.79,3.31,35.82,2008.0,Racing,Nintendo
3,4,Wii Sports Resort,Wii,15.75,11.01,3.28,2.96,33.00,2009.0,Sports,Nintendo
7,8,Wii Play,Wii,14.03,9.20,2.93,2.85,29.02,2006.0,Misc,Nintendo
8,9,New Super Mario Bros. Wii,Wii,14.59,7.06,4.70,2.26,28.62,2009.0,Platform,Nintendo
13,14,Wii Fit,Wii,8.94,8.03,3.60,2.15,22.72,2007.0,Sports,Nintendo
14,15,Wii Fit Plus,Wii,9.09,8.59,2.53,1.79,22.00,2009.0,Sports,Nintendo
39,40,Super Smash Bros. Brawl,Wii,6.75,2.61,2.66,1.02,13.04,2008.0,Fighting,Nintendo
48,49,Super Mario Galaxy,Wii,6.16,3.40,1.20,0.76,11.52,2007.0,Platform,Nintendo
78,79,Wii Party,Wii,1.79,3.53,2.49,0.68,8.49,2010.0,Misc,Nintendo
80,81,Mario Party 8,Wii,3.81,2.30,1.58,0.73,8.42,2007.0,Misc,Nintendo
91,92,Super Mario Galaxy 2,Wii,3.66,2.42,0.98,0.64,7.69,2010.0,Platform,Nintendo
100,101,The Legend of Zelda: Twilight Princess,Wii,3.83,2.19,0.60,0.70,7.31,2006.0,Action,Nintendo
125,126,Donkey Kong Country Returns,Wii,3.25,1.84,1.03,0.47,6.59,2010.0,Platform,Nintendo
206,207,Link's Crossbow Training,Wii,3.06,1.18,0.29,0.46,5.00,2007.0,Shooter,Nintendo
226,227,Animal Crossing: City Folk,Wii,1.87,1.12,1.32,0.37,4.68,2008.0,Simulation,Nintendo
284,285,The Legend of Zelda: Skyward Sword,Wii,2.14,1.20,0.37,0.40,4.10,2011.0,Action,Nintendo
320,321,Big Brain Academy: Wii Degree,Wii,1.06,1.93,0.41,0.43,3.82,2007.0,Misc,Nintendo
329,330,Super Paper Mario,Wii,1.98,0.88,0.59,0.32,3.76,2007.0,Platform,Nintendo
405,406,Mario Party 9,Wii,1.15,1.17,0.76,0.24,3.32,2012.0,Misc,Nintendo
412,413,Wii Music,Wii,1.36,1.13,0.46,0.32,3.27,2008.0,Misc,Nintendo
490,491,WarioWare: Smooth Moves,Wii,0.87,1.06,0.73,0.26,2.92,2006.0,Puzzle,Nintendo
581,582,Mario Strikers Charged,Wii,1.07,1.06,0.24,0.25,2.62,2007.0,Sports,Nintendo
587,588,Super Mario All-Stars: Limited Edition,Wii,1.02,0.52,0.92,0.14,2.60,2010.0,Platform,Nintendo
718,720,Monster Hunter Tri,Wii,0.67,0.41,1.05,0.11,2.25,2009.0,Role-Playing,Nintendo
773,775,Kirby's Epic Yarn,Wii,1.47,0.09,0.45,0.11,2.12,2010.0,Platform,Nintendo
781,783,Mario Sports Mix,Wii,0.90,0.45,0.63,0.13,2.11,2010.0,Sports,Nintendo
892,894,Mario Super Sluggers,Wii,1.51,0.00,0.29,0.12,1.93,2008.0,Sports,Nintendo
955,957,Metroid Prime 3: Corruption,Wii,0.91,0.74,0.07,0.09,1.82,2007.0,Shooter,Nintendo
1053,1055,Kirby's Return to Dreamland,Wii,0.62,0.21,0.79,0.08,1.70,2011.0,Platform,Nintendo
1139,1141,Pokemon Battle Revolution,Wii,0.80,0.38,0.30,0.13,1.61,2006.0,Role-Playing,Nintendo
1275,1277,New Play Control! Mario Power Tennis,Wii,0.37,0.69,0.28,0.14,1.48,2009.0,Sports,Nintendo
1374,1376,Metroid: Other M,Wii,0.87,0.31,0.13,0.10,1.41,2010.0,Action,Nintendo
1682,1684,PokéPark Wii: Pikachu's Adventure,Wii,0.55,0.17,0.42,0.06,1.20,2009.0,Adventure,Nintendo
1723,1725,Wario Land: Shake It!,Wii,0.60,0.31,0.15,0.11,1.17,2008.0,Platform,Nintendo
1890,1892,Endless Ocean,Wii,0.44,0.47,0.09,0.09,1.09,2007.0,Adventure,Nintendo

In [100]:
# 고급 불리언 인덱싱

# 1. isin()을 이용한 불리언 인덱싱

df[((df['Platform'] == 'PS4') | (df['Platform'] == 'XOne') | (df['Platform'] == 'PC')) & (df['Genre'] == 'Action')]

# 더 코드가 간결해지는 방법은?
Pf_list = ['PS4', 'XOne', 'PC']
df[(df['Platform'].isin(Pf_list)) & (df['Genre'] == 'Action')]

,GAME_ID,Name,Platform,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Year,Genre,Publisher
44,45,Grand Theft Auto V,PS4,3.80,5.81,0.36,2.02,11.98,2014.0,Action,Take-Two Interactive
197,198,Grand Theft Auto V,XOne,2.66,2.01,0.00,0.41,5.08,2014.0,Action,Take-Two Interactive
236,237,The Last of Us,PS4,1.78,1.87,0.07,0.82,4.55,2014.0,Action,Sony Computer Entertainment
243,244,Uncharted: The Nathan Drake Collection,PS4,1.96,1.69,0.08,0.74,4.47,2015.0,Action,Sony Computer Entertainment
280,281,Watch Dogs,PS4,1.40,1.86,0.11,0.77,4.14,2014.0,Action,Ubisoft
...,...,...,...,...,...,...,...,...,...,...,...
16452,16455,Rugby League Live 3,XOne,0.00,0.01,0.00,0.00,0.01,2015.0,Action,Tru Blu Entertainment
16509,16512,Trine,PC,0.00,0.01,0.00,0.00,0.01,2009.0,Action,Nobilis
16531,16534,Hitman (2016),XOne,0.00,0.01,0.00,0.00,0.01,2016.0,Action,Square Enix
16537,16540,Transformers: Fall of Cybertron,PC,0.01,0.00,0.00,0.00,0.01,2012.0,Action,Activision
16550,16553,God Eater Off Shot: Tachibana Sakuya-hen Twin ...,PS4,0.00,0.00,0.01,0.00,0.01,2016.0,Action,Namco Bandai Games

In [101]:
# 2. isna()를 이용한 불리언 인덱싱

df[['Name','Platform','Publisher']][df['Publisher'].isna()]

                                                    Name Platform Publisher
470                           wwe Smackdown vs. Raw 2006      PS2       NaN
1303                                      Triple Play 99       PS       NaN
1662        Shrek / Shrek 2 2-in-1 Gameboy Advance Video      GBA       NaN
2222                                  Bentley's Hackpack      GBA       NaN
3159   Nicktoons Collection: Game Boy Advance Video V...      GBA       NaN
3166   SpongeBob SquarePants: Game Boy Advance Video ...      GBA       NaN
3766   SpongeBob SquarePants: Game Boy Advance Video ...      GBA       NaN
4145                                  Sonic the Hedgehog      PS3       NaN
4526   The Fairly Odd Parents: Game Boy Advance Video...      GBA       NaN
4635   The Fairly Odd Parents: Game Boy Advance Video...      GBA       NaN
5302       Dragon Ball Z: Budokai Tenkaichi 2 (JP sales)      Wii       NaN
5647   Cartoon Network Collection: Game Boy Advance V...      GBA       NaN
6272   The Legend of Zelda: The Minish Cap(weekly JP ...      GBA       NaN
6437            Sonic X: Game Boy Advance Video Volume 1      GBA       NaN
6562   Dora the Explorer: Game Boy Advance Video Volu...      GBA       NaN
6648   Cartoon Network Collection: Game Boy Advance V...      GBA       NaN
6849      All Grown Up!: Game Boy Advance Video Volume 1      GBA       NaN
7208   Nicktoons Collection: Game Boy Advance Video V...      GBA       NaN
7351                      Yu Yu Hakusho: Dark Tournament      PS2       NaN
7470   SpongeBob SquarePants: Game Boy Advance Video ...      GBA       NaN
7953                    Thomas the Tank Engine & Friends      GBA       NaN
8330     Dragon Ball GT: Game Boy Advance Video Volume 1      GBA       NaN
8341   Codename: Kids Next Door: Game Boy Advance Vid...      GBA       NaN
8368   Teenage Mutant Ninja Turtles: Game Boy Advance...      GBA       NaN
8503                                        Stronghold 3       PC       NaN
8770   Cartoon Network Collection: Game Boy Advance V...      GBA       NaN
8848   Pokémon: Johto Photo Finish: Game Boy Advance ...      GBA       NaN
8896   Strawberry Shortcake: Game Boy Advance Video V...      GBA       NaN
9517                              Farming Simulator 2011       PC       NaN
9749   Super Robot Wars OG Saga: Masou Kishin II - Re...      PSP       NaN
10382                   Disney Channel Collection Vol. 1      GBA       NaN
10494             Atsumare! Power Pro Kun no DS Koushien       DS       NaN
11076                       Action Man-Operation Extreme       PS       NaN
11526  Cartoon Network Collection: Game Boy Advance V...      GBA       NaN
12487                               Chou Soujuu Mecha MG       DS       NaN
12517       Prinny: Can I Really Be The Hero? (US sales)      PSP       NaN
13278                     Monster Hunter Frontier Online      PS3       NaN
13672                          B.L.U.E.: Legend of Water       PS       NaN
13962                                     World of Tanks     X360       NaN
14087                                       Housekeeping       DS       NaN
14296                                Bikkuriman Daijiten       DS       NaN
14311                                      Silverlicious       DS       NaN
14698                                 UK Truck Simulator       PC       NaN
14942  Umineko no Naku Koro ni San: Shinjitsu to Gens...      PS3       NaN
15056                                            Xia-Xia       DS       NaN
15261                                       Mario Tennis      3DS       NaN
15325  Nicktoons Collection: Game Boy Advance Video V...      GBA       NaN
15353                   Demolition Company: Gold Edition       PC       NaN
15788  Moshi, Kono Sekai ni Kami-sama ga Iru to suru ...      PSV       NaN
15915                                       Dream Dancer       DS       NaN
16191                    Homeworld Remastered Collection       PC       NaN
16198             AKB1/48: Idol to Guam de Koishitara...     X360       NaN
16208  Super Robot Monkey Team: Game Boy Advance Vide...      GBA       NaN
16229                        Brothers in Arms: Furious 4     X360       NaN
16367                                  Dance with Devils      PSV       NaN
16494                    Legends of Oz: Dorothy's Return      3DS       NaN
16543                             Driving Simulator 2011       PC       NaN
16553                                     Bound By Flame     X360       NaN

In [102]:
# 문자열을 검색할 때 - .str.contains()

df[df['Name'].str.contains('zelda', case=False, na=False)]
# case=False: True는 대소문자를 구분하고, False는 구분하지 않습니다.
# na=False: 중간에 NaN이 있으면 그냥 False를 뱉고 검색을 멈추지 않는 조건입니다.

,GAME_ID,Name,Platform,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Year,Genre,Publisher
94,95,The Legend of Zelda: Ocarina of Time,N64,4.10,1.89,1.45,0.16,7.60,1998.0,Action,Nintendo
100,101,The Legend of Zelda: Twilight Princess,Wii,3.83,2.19,0.60,0.70,7.31,2006.0,Action,Nintendo
127,128,The Legend of Zelda,NES,3.74,0.93,1.69,0.14,6.51,1986.0,Action,Nintendo
186,187,The Legend of Zelda: Phantom Hourglass,DS,1.90,1.83,0.95,0.49,5.17,2007.0,Action,Nintendo
231,232,The Legend of Zelda: A Link to the Past,SNES,2.42,0.91,1.15,0.13,4.61,1991.0,Action,Nintendo
232,233,The Legend of Zelda: The Wind Waker,GC,2.60,0.99,0.89,0.13,4.60,2002.0,Action,Nintendo
251,252,Zelda II: The Adventure of Link,NES,2.19,0.50,1.61,0.08,4.38,1987.0,Adventure,Nintendo
268,269,The Legend of Zelda: Ocarina of Time,3DS,2.03,1.27,0.62,0.30,4.21,2011.0,Action,Nintendo
284,285,The Legend of Zelda: Skyward Sword,Wii,2.14,1.20,0.37,0.40,4.10,2011.0,Action,Nintendo
318,319,The Legend of Zelda: Link's Awakening,GB,2.21,0.96,0.54,0.13,3.83,1992.0,Action,Nintendo
396,397,The Legend of Zelda: Spirit Tracks,DS,1.43,0.94,0.74,0.27,3.38,2009.0,Action,Nintendo
398,399,The Legend of Zelda: Majora's Mask,N64,1.90,0.67,0.73,0.06,3.36,2000.0,Action,Nintendo
454,455,The Legend of Zelda: A Link Between Worlds,3DS,1.40,0.99,0.46,0.22,3.07,2013.0,Action,Nintendo
551,552,The Legend of Zelda: A Link to the Past,GBA,1.75,0.52,0.33,0.10,2.70,2002.0,Action,Nintendo
680,682,The Legend of Zelda: Majora's Mask 3D,3DS,1.14,0.54,0.47,0.17,2.32,2015.0,Action,Nintendo
728,730,The Legend of Zelda: Link's Awakening DX,GB,1.00,0.63,0.45,0.13,2.22,1998.0,Adventure,Nintendo
894,896,The Legend of Zelda: Oracle of Ages,GB,0.92,0.53,0.41,0.06,1.92,2001.0,Action,Nintendo
923,925,The Legend of Zelda: Oracle of Seasons,GB,0.87,0.52,0.41,0.06,1.86,2001.0,Adventure,Nintendo
978,980,The Legend of Zelda: The Wind Waker,WiiU,0.93,0.57,0.14,0.13,1.77,2013.0,Action,Nintendo
1160,1162,The Legend of Zelda: Twilight Princess,GC,1.15,0.36,0.04,0.04,1.59,2006.0,Action,Nintendo
1357,1359,The Legend of Zelda: The Minish Cap,GBA,0.89,0.22,0.22,0.10,1.42,2004.0,Action,Nintendo
1850,1852,The Legend of Zelda: Tri Force Heroes,3DS,0.52,0.33,0.17,0.08,1.10,2015.0,Action,Nintendo
2212,2214,The Legend of Zelda: Twilight Princess HD,WiiU,0.48,0.30,0.08,0.08,0.94,2016.0,Action,Nintendo
2333,2335,Classic NES Series: The Legend of Zelda,GBA,0.46,0.17,0.24,0.02,0.89,2004.0,Adventure,Nintendo
2540,2542,The Legend of Zelda: Four Swords Adventures,GC,0.63,0.16,0.00,0.02,0.81,2004.0,Action,Nintendo
2937,2939,Classic NES Series: Zelda II: The Adventure of...,GBA,0.37,0.14,0.17,0.01,0.70,2004.0,Adventure,Nintendo
6272,6274,The Legend of Zelda: The Minish Cap(weekly JP ...,GBA,0.00,0.00,0.27,0.01,0.27,NaN,Action,NaN

In [103]:
# 실수를 검색할 때 - np.isclose()

df[np.isclose(df['Year'], 2015.0)]

,GAME_ID,Name,Platform,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Year,Genre,Publisher
33,34,Call of Duty: Black Ops 3,PS4,5.77,5.81,0.35,2.31,14.24,2015.0,Shooter,Activision
77,78,FIFA 16,PS4,1.11,6.06,0.06,1.26,8.49,2015.0,Sports,Electronic Arts
92,93,Star Wars Battlefront (2015),PS4,2.93,3.29,0.22,1.23,7.67,2015.0,Shooter,Electronic Arts
101,102,Call of Duty: Black Ops 3,XOne,4.52,2.09,0.01,0.67,7.30,2015.0,Shooter,Activision
109,110,Fallout 4,PS4,2.47,3.15,0.24,1.10,6.96,2015.0,Role-Playing,Bethesda Softworks
...,...,...,...,...,...,...,...,...,...,...,...
16499,16502,Irotoridori no Sekai: World's End Re-Birth,PSV,0.00,0.00,0.01,0.00,0.01,2015.0,Action,HuneX
16528,16531,Kiniro no Corda 3,3DS,0.00,0.00,0.01,0.00,0.01,2015.0,Adventure,Tecmo Koei
16542,16545,Mario & Luigi: Paper Jam & Mario Kart 7 Double...,3DS,0.00,0.00,0.01,0.00,0.01,2015.0,Misc,Nintendo
16548,16551,Hakuoki: Reimeiroku - Omouhase Kara,PSV,0.00,0.00,0.01,0.00,0.01,2015.0,Action,Idea Factory
16565,16568,Teslagrad,PSV,0.00,0.01,0.00,0.00,0.01,2015.0,Platform,Rain Games

In [104]:
# 데이터프레임 정렬 - 단일 기준

df.sort_values(by='JP_Sales', ascending=False).head()

,GAME_ID,Name,Platform,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Year,Genre,Publisher
4,5,Pokemon Red/Pokemon Blue,GB,11.27,8.89,10.22,1.00,31.37,1996.0,Role-Playing,Nintendo
12,13,Pokemon Gold/Pokemon Silver,GB,9.00,6.18,7.20,0.71,23.10,1999.0,Role-Playing,Nintendo
1,2,Super Mario Bros.,NES,29.08,3.58,6.81,0.77,40.24,1985.0,Platform,Nintendo
6,7,New Super Mario Bros.,DS,11.38,9.23,6.50,2.90,30.01,2006.0,Platform,Nintendo
20,21,Pokemon Diamond/Pokemon Pearl,DS,6.42,4.52,6.04,1.37,18.36,2006.0,Role-Playing,Nintendo

In [105]:
# 데이터프레임 정렬 - 다중 기준

df[['Year','Name']].sort_values(by=['Year', 'Name'], ascending=[False, True])

         Year                                              Name
5957   2020.0                            Imagine: Makeup Artist
16438  2017.0                  Brothers Conflict: Precious Baby
14390  2017.0  Phantasy Star Online 2 Episode 4: Deluxe Package
16241  2017.0  Phantasy Star Online 2 Episode 4: Deluxe Package
14005  2016.0                             12-Sai. Koisuru Diary
...       ...                                               ...
7351      NaN                    Yu Yu Hakusho: Dark Tournament
15476     NaN        Yu-Gi-Oh! 5D's Wheelie Breakers (JP sales)
11409     NaN                          Zero: Tsukihami no Kamen
8899      NaN                                    eJay Clubworld
470       NaN                        wwe Smackdown vs. Raw 2006

[16598 rows x 2 columns]

In [106]:
# 인덱스 재설정

my_df = df[['Year','Name']][df['Publisher'] == 'Nintendo'].sort_values(by=['Year', 'Name'], ascending=[False, True])

print(my_df.head())

         Year                                         Name
12954  2016.0                              Culdcept Revolt
11010  2016.0                           Disney Art Academy
4658   2016.0                              Hyrule Warriors
2448   2016.0                        Kirby: Planet Robobot
4261   2016.0  Mario & Sonic at the Rio 2016 Olympic Games

In [107]:
# drop=True: 기존 인덱스를 별개의 열로 남기지 않는 옵션
print(my_df.reset_index(drop=True).head(3))

     Year                Name
0  2016.0     Culdcept Revolt
1  2016.0  Disney Art Academy
2  2016.0     Hyrule Warriors

In [108]:
# drop=False일 때는 이렇습니다.
print(my_df.reset_index(drop=False).head(3))

   index    Year                Name
0  12954  2016.0     Culdcept Revolt
1  11010  2016.0  Disney Art Academy
2   4658  2016.0     Hyrule Warriors

# 4. 값 매핑과 대체

In [109]:
# 열 이름 바꾸기

# 'Year'를 'Release_Year'로, 'Name'를 'Title'로 바꾸기
df = df.rename(columns={'Year':'Release_Year', 'Name':'Title'})

print(df.columns)

Index(['GAME_ID', 'Title', 'Platform', 'NA_Sales', 'EU_Sales', 'JP_Sales',
       'Other_Sales', 'Global_Sales', 'Release_Year', 'Genre', 'Publisher'],
      dtype='object')

In [110]:
# astype(바꿀 자료형) - 자료형 변경
# 원본 데이터셋은 Year가 float입니다. 이를 정수형으로 바꿔 봅시다

# 그 전에 NaN을 일단 0으로 바꿔줍시다. (NaN이 있으면 변환이 안되므로)
df['Release_Year'] = df['Release_Year'].fillna(0)
df['Release_Year'] = df['Release_Year'].astype(int)

print(df.dtypes)

GAME_ID           int64
Title            object
Platform         object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
Release_Year      int64
Genre            object
Publisher        object
dtype: object

In [111]:
# replace()

# 'X360'을 알아보기 쉽게 'Xbox_360'으로 바꾸기
df['Platform'] = df['Platform'].replace('X360', 'Xbox_360')

# 여러 개를 동시에 바꾸고 싶다면 리스트로 묶어주면 됩니다.
# df['Platform'] = df['Platform'].replace(['PS3', 'PS4'], ['PlayStation3', 'PlayStation4'])

In [112]:
# 판다스로 원핫인코딩 - pd.get_dummies()

df_genre = df[['Title','Genre']]

df_encoded = pd.get_dummies(df_genre, columns=['Genre'], drop_first=True)

df_encoded.head(3)

,Title,Genre_Adventure,Genre_Fighting,Genre_Misc,Genre_Platform,Genre_Puzzle,Genre_Racing,Genre_Role-Playing,Genre_Shooter,Genre_Simulation,Genre_Sports,Genre_Strategy
0,Wii Sports,False,False,False,False,False,False,False,False,False,True,False
1,Super Mario Bros.,False,False,False,True,False,False,False,False,False,False,False
2,Mario Kart Wii,False,False,False,False,False,True,False,False,False,False,False

In [113]:
# drop_first를 안 하면?

df_encoded_no_drop = pd.get_dummies(df_genre, columns=['Genre'])
df_encoded_no_drop.head(3)
# 위랑 다르게 Genre_Action이 있네요

,Title,Genre_Action,Genre_Adventure,Genre_Fighting,Genre_Misc,Genre_Platform,Genre_Puzzle,Genre_Racing,Genre_Role-Playing,Genre_Shooter,Genre_Simulation,Genre_Sports,Genre_Strategy
0,Wii Sports,False,False,False,False,False,False,False,False,False,False,True,False
1,Super Mario Bros.,False,False,False,False,True,False,False,False,False,False,False,False
2,Mario Kart Wii,False,False,False,False,False,False,True,False,False,False,False,False

In [114]:
# map(딕셔너리)으로 규칙에 따라 일괄 대체

rule = {'Adelie':'Ad', 'Chinstrap':'Ch', 'Gentoo':'Gt'}

# 축약된 열을 만들 때
# df_peng['species_short'] = df_peng['species'].map(rule)

# 열을 아예 바꿔버릴때
# df_peng['species'] = df_peng['species'].map(rule)

In [115]:
# apply(함수)

# 글로벌 판매량이 백만장 이상이면 밀리언셀러로 표기해 봅시다
df['Hit'] = df['Global_Sales'].apply(lambda x: '밀리언셀러' if x >= 1.0 else '일반')

print(df['Hit'].value_counts(normalize=True))

Hit
일반       0.874623
밀리언셀러    0.125377
Name: proportion, dtype: float64

In [116]:
df['JP_RPG_Hit'] = df.apply(
    lambda x: '밀리언셀러' if (x['JP_Sales'] >= 1.0) and (x['Genre'] == 'Role-Playing') else '일반', 
    axis=1  # axis를 지정해 줘야 합니다.
)

print(df['JP_RPG_Hit'].value_counts(normalize=True))

JP_RPG_Hit
일반       0.995421
밀리언셀러    0.004579
Name: proportion, dtype: float64

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   GAME_ID       16598 non-null  int64
 1   Title         16598 non-null  object
 2   Platform      16598 non-null  object
 3   NA_Sales      16598 non-null  float64
 4   EU_Sales      16598 non-null  float64
 5   JP_Sales      16598 non-null  float64
 6   Other_Sales   16598 non-null  float64
 7   Global_Sales  16598 non-null  float64
 8   Release_Year  16598 non-null  int64
 9   Genre         16598 non-null  object
 10  Publisher     16540 non-null  object
 11  Hit           16598 non-null  object
 12  JP_RPG_Hit    16598 non-null  object
dtypes: float64(5), int64(2), object(6)
memory usage: 1.6+ MB

In [118]:
# 아까 float -> int 변환하기 전에 결측을 0으로 바꿔줬는데, 이번에는 드랍할게요.
df = df[df['Release_Year'] != 0]

In [119]:
df['Release_Year']

0        2006
1        1985
2        2008
3        2009
4        1996
         ...
16593    2002
16594    2003
16595    2008
16596    2010
16597    2003
Name: Release_Year, Length: 16327, dtype: int64

In [120]:
# 실습 3: apply와 람다함수로 Decade라는 열을 만들어 봅시다.
df['Release_Year']=df['Release_Year'].astype(str)
df['Decade'] = df['Release_Year'].apply(lambda x: x[:3] + '0s')

print(df['Decade'].value_counts(normalize=True))

Decade
2000s    0.563974
2010s    0.315061
1990s    0.108348
1980s    0.012556
2020s    0.000061
Name: proportion, dtype: float64

# 5. 그룹화, 집계함수

In [121]:
# groupby()

# 각 플랫폼별로 글로벌 판매량의 합계는 얼마일까?

df.groupby('Platform')['Global_Sales'].sum() # -> 시리즈

df.groupby('Platform')[['Global_Sales']].sum() # -> 데이터프레임 (fancy 방식)

          Global_Sales
Platform
2600             86.57
3DO               0.10
3DS             246.28
DC               15.97
DS              818.96
GB              254.42
GBA             313.56
GC              197.14
GEN              28.36
GG                0.04
N64             218.21
NES             251.07
NG                1.44
PC              255.05
PCFX              0.03
PS              727.39
PS2            1233.46
PS3             949.35
PS4             278.10
PSP             291.71
PSV              61.63
SAT              33.59
SCD               1.87
SNES            200.05
TG16              0.16
WS                1.42
Wii             909.81
WiiU             81.86
XB              252.09
XOne            141.06
Xbox_360        969.61

In [122]:
# 판매량 합계가 많은 순서대로 보기

# Series이니까.. 정렬을 할 수 있겠죠?
print(type(df.groupby('Platform')['Global_Sales'].sum()))

df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).head()

<class 'pandas.core.series.Series'>

Platform
PS2         1233.46
Xbox_360     969.61
PS3          949.35
Wii          909.81
DS           818.96
Name: Global_Sales, dtype: float64

In [123]:
# agg()

# 리스트 [ ] 안에 원하는 집계함수 이름들을 문자열로 넣어줍니다.
# 저는 판매량 평균이 높은 순으로 정렬도 해봤어요

df.groupby('Platform')['Global_Sales'].agg(['sum', 'mean', 'count']).sort_values(by='mean', ascending=False).head(10)

             sum      mean  count
Platform
GB        254.42  2.622887     97
NES       251.07  2.561939     98
GEN        28.36  1.050370     27
SNES      200.05  0.837029    239
PS4       278.10  0.827679    336
Xbox_360  969.61  0.785109   1235
2600       86.57  0.746293    116
PS3       949.35  0.728029   1304
Wii       909.81  0.705279   1290
N64       218.21  0.690538    316

In [124]:
# 참고 - 사용자 정의 함수를 agg에 쓰기

def get_range(x):
    return x.max() - x.min()

df.groupby('Publisher')['Global_Sales'].agg(
    ['max', 'min', get_range, lambda x: x.max() / x.mean()]
).sort_values(by='max', ascending=False).head(10)

                               max   min  get_range  <lambda_0>
Publisher
Nintendo                     82.74  0.01      82.73   32.271952
Microsoft Game Studios       21.82  0.01      21.81   16.778469
Take-Two Interactive         21.40  0.01      21.39   22.080641
Sony Computer Entertainment  14.98  0.01      14.97   16.823146
Activision                   14.76  0.01      14.75   19.764295
Ubisoft                      10.26  0.01      10.25   19.889935
Bethesda Softworks            8.84  0.01       8.83    7.481418
Electronic Arts               8.49  0.01       8.48   10.397123
Sega                          8.06  0.01       8.05   18.817584
SquareSoft                    7.86  0.05       7.81    7.089679

In [128]:
# 실습 4는 여기에!

df.groupby('Genre')['Global_Sales'].agg(
    최대판매량=('max'),
    최소판매량=('min'),
    판매량격차=(get_range),
    최대평균비율=(lambda x: x.max() / x.mean())
).sort_values(by='최대판매량', ascending=False).head(10)

              최대판매량  최소판매량  판매량격차      최대평균비율
Genre
Sports        82.74   0.01  82.73  145.605817
Platform      40.24   0.01  40.23   42.513707
Racing        35.82   0.01  35.81   60.425334
Role-Playing  31.37   0.01  31.36   49.949418
Puzzle        30.26   0.01  30.25   71.333746
Misc          29.02   0.01  29.01   62.215341
Shooter       28.31   0.01  28.30   35.366810
Simulation    24.76   0.01  24.75   54.005434
Action        21.40   0.01  21.39   40.405716
Fighting      13.04   0.01  13.03   24.550028

# 파깃스 수고 많으셨어요 !!!

### 항상 고맙습니다 😊🙂‍↕️